In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
import os

In [ ]:
data_file_path = os.path.abspath(os.path.join(os.pardir,'data','cleaned_AG.csv'))
export_file_path = os.path.abspath(os.path.join(os.pardir,'data','bag_of_words_training_data.csv'))

# data_file_path = os.path.abspath(os.path.join(os.pardir,'data','cleaned_bing.csv'))
# export_file_path = os.path.abspath(os.path.join(os.pardir,'data','bag_of_words_bing_data.csv'))

In [2]:
data = pd.read_csv(data_file_path)
data.head()

,News Category,Documents,Word Count,Noun Phrases,Noun Count,Adjective Count,Verb Count
0,business,wall st bear claw back black reuters reuters s...,18,4,12,3,2
1,business,carlyle look toward commercial aerospace reute...,27,5,15,4,3
2,business,oil economy cloud stock outlook reuters reuter...,24,5,17,4,2
3,business,iraq halt oil export main southern pipeline re...,28,3,19,6,3
4,business,oil price soar time record posing new menace e...,28,4,16,7,3

# Bag of Words

In [46]:
#bag of words
vectorizer = CountVectorizer(max_features=1000)
X = vectorizer.fit_transform(data['Documents'].values)

denselist = X.todense().tolist()
df = pd.DataFrame(denselist, columns=vectorizer.get_feature_names())
bag_of_words = pd.concat([data['News Category'],df],axis=1)
bag_of_words.head()

,News Category,access,according,accused,acquisition,across,action,activity,ad,add,...,yahoo,yankee,yard,yasser,year,yesterday,yet,york,young,yukos
0,business,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,business,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,business,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,business,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,business,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#export bag of words feature data
bag_of_words.to_csv(export_file_path,index=False)